export default {
  // ACTIONS
  JOBFIELDS_RECEIVE_DATA: 'JOBFIELDS_RECEIVE_DATA',
  JOBFIELDS_RECEIVE_DATA_ERROR: 'JOBFIELDS_RECEIVE_DATA_ERROR',
  JOBFIELD_AWAIT_CREATION_RESPONSE: 'JOBFIELD_AWAIT_CREATION_RESPONSE',
  JOBFIELD_RECEIVE_CREATION_RESPONSE: 'JOBFIELD_RECEIVE_CREATION_RESPONSE',
  JOBFIELD_EDIT: 'JOBFIELD_EDIT',
  JOBFIELD_EDIT_FINISH: 'JOBFIELD_EDIT_FINISH',
  JOBFIELD_EDIT_SUBMIT: 'JOBFIELD_EDIT_SUBMIT',

  // STATES
  JOBFIELD_EDITING: 'JOBFIELD_EDITING',
  JOBFIELD_SUBMITTING: 'JOBFIELD_SUBMITTING',
};
