 export default {
  // ACTIONS
  JOBS_RECEIVE_DATA: 'JOBS_RECEIVE_DATA',
  JOBS_RECEIVE_DATA_ERROR: 'JOBS_RECEIVE_DATA_ERROR',
  JOB_AWAIT_CREATION_RESPONSE: 'JOB_AWAIT_CREATION_RESPONSE',
  JOB_RECEIVE_CREATION_RESPONSE: 'JOB_RECEIVE_CREATION_RESPONSE',
  JOB_EDIT: 'JOB_EDIT',
  JOB_EDIT_FINISH: 'JOB_EDIT_FINISH',
  JOB_EDIT_SUBMIT: 'JOB_EDIT_SUBMIT',
  SEARCH_RECEIVE_DATA:'SEARCH_RECEIVE_DATA',
  SEARCH_RECEIVE_DATA_ERROR: 'SEARCH_RECEIVE_DATA_ERROR',
  // STATES
  JOB_EDITING: 'JOB_EDITING',
  JOB_SUBMITTING: 'JOB_SUBMITTING',
};