export default {
  // ACTIONS
  REGIONS_RECEIVE_DATA: 'REGIONS_RECEIVE_DATA',
  REGIONS_RECEIVE_DATA_ERROR: 'REGIONS_RECEIVE_DATA_ERROR',
  REGION_AWAIT_CREATION_RESPONSE: 'REGION_AWAIT_CREATION_RESPONSE',
  REGION_RECEIVE_CREATION_RESPONSE: 'REGION_RECEIVE_CREATION_RESPONSE',
  REGION_EDIT: 'REGION_EDIT',
  REGION_EDIT_FINISH: 'REGION_EDIT_FINISH',
  REGION_EDIT_SUBMIT: 'REGION_EDIT_SUBMIT',

  // STATES
  REGION_EDITING: 'REGION_EDITING',
  REGION_SUBMITTING: 'REGION_SUBMITTING',
};
