export default {
  // ACTIONS
  SCOPES_RECEIVE_DATA: 'SCOPES_RECEIVE_DATA',
  SCOPES_RECEIVE_DATA_ERROR: 'SCOPES_RECEIVE_DATA_ERROR',
  SCOPE_AWAIT_CREATION_RESPONSE: 'SCOPE_AWAIT_CREATION_RESPONSE',
  SCOPE_RECEIVE_CREATION_RESPONSE: 'SCOPE_RECEIVE_CREATION_RESPONSE',
  SCOPE_EDIT: 'SCOPE_EDIT',
  SCOPE_EDIT_FINISH: 'SCOPE_EDIT_FINISH',
  SCOPE_EDIT_SUBMIT: 'SCOPE_EDIT_SUBMIT',
  SCOPE_CHOOSESCOPE:'SCOPE_CHOOSESCOPE',

  // STATES
  SCOPE_EDITING: 'SCOPE_EDITING',
  SCOPE_SUBMITTING: 'SCOPE_SUBMITTING',
};
